### ISSUE TITLE
ETQA abbreviations (and other lookups) need to be indexed for search

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#104]
I can search successfully for "media, information and communication" but not for MICTSETA. I think searches for courses under a SETA/ETQA will tend to use the abbreviation. 

btw, search clauses in " " are treated as one search term which is a great feature.

**Comment by cchristelis** [comment]
This is should be looked at in light of this comment in #48 https://github.com/kartoza/feti/issues/48#issuecomment-124018752.
