### ISSUE TITLE
users must have a way of providing feedback

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#105]
FETI needs a way to get user feedback, whether it is about bugs in the application, data issues other questions. So a contact popup, contact form, or other method will be needed. 

Await input from FETI staff before proceeding.

**Comment by cchristelis** [comment]
Hi @MariaSolovyeva, if there is a place for this in our layout. Once this is the case, please close.

**Comment by MariaSolovyeva** [comment]
Hi @cchristelis and @gubuntu , it was not placed in the design, I think the nice place for it will be here, with a link to a pop-up, what do you think?
![feedback](https://cloud.githubusercontent.com/assets/10400420/22204263/08bafc8a-e182-11e6-8860-eb4c7c10e494.png)

**Comment by cchristelis** [comment]
LGTM
