### ISSUE TITLE
clean up display - only show data that is present

### ISSUE THREAD

**Issue by tmcbride1967** [kartoza/feti#106]
This still appears as 
College of Cape Town FET College - Cnr. NY1 & Ngambu Street Guguletu 7750false,false,1
Not sure if this '"false,false,1" appears elsewhere. 
Tim.

**Comment by cchristelis** [comment]
@lucernae, could you have a look at this in conjunction with #107. I think they are very similar.

**Comment by gubuntu** [comment]
booleans and nulls should not appear in such a raw state if at all. Either leave blank or do something like a greyed-out 'xyz field missing'

**Comment by lucernae** [comment]
After tracking it down, apparently it was coming directly from the data.
To be precise, from the campus field of campus models, which is strange.

It means we have to standardize again data import from initial feti database?

**Comment by gubuntu** [comment]
The app should use the campus field, as you say, the app does not need a fix here. I think @gustry used the provider's address as campus name in the absence of another candidate for campus name. So, either a tweaked import or a post-import data fix is in order. I proposed the following:
 - if there is an obvious campus name, use it
 - for providers with one campus, default to 'main campus' for campus name or pull suburb from address and create '<suburb> campus'
 - for providers with more than one address, pull suburb or another address differentiator into campus name
I don't think we need to rank campuses or even identify a main and secondary campuses, they just need to have an identifier. 

For the generation of addresses in the first place, they should not be populated with 'false,false,1'.

**Comment by Gustry** [comment]
I've checked in the database. There is only one campus with ``false`` in the name.

About ``'Cnr. NY1 & Ngambu Street Guguletu 7750false,false,1'``, this address is in the original MS Access table ``providers_courses``.

@gubuntu Do we need to review the import script ?

**Comment by cchristelis** [comment]
This is no longer an issue.
