### ISSUE TITLE
Popup bubble: look and feel!

### ISSUE THREAD

**Issue by tmcbride1967** [kartoza/feti#107]
I wanted the bubble to highlight 1) Main Provider 2) Suburb/campus 3) Course + Level. Here is a suggestion of what I had in mind. (I don't know GitHub but some of this was supposed to appear in bold)

CURRENT
Zambli220 PTY LTD T/A POWDERMET (Atlantis) - John Vani Niekerk Street, Atlantis
7349
Courses : 
•	Manufacturing, Engineering and Related Services Sector Education and Training Authority : National Certificate in Metal and Engineering Manufacturing Processes: NQF Level 4
•	Manufacturing, Engineering and Related Services Sector Education and Training Authority : National Certificate in Mechanical Engineering (Machining): NQF Level 4
•	Manufacturing, Engineering and Related Services Sector Education and Training Authority : National Certificate in Metal and Engineering Manufacturing Processes: NQF Level 3
•	Manufacturing, Engineering and Related Services Sector Education and Training Authority : National Certificate in Metal and Engineering Manufacturing Processes: NQF Level 2
•	

PROPOSED

Zambli220 PTY LTD T/A POWDERMET (Atlantis) <bold>, <larger or coloured font.
Site: Atlantis <bold>
 John Vani Niekerk Street, Atlantis, 7349
Website: 
Phone:
Courses : 
•	National Certificate in Metal and Engineering Manufacturing Processes: NQF Level 4 <bold>(MERSETA) <abbreviation only, not bold>
•	National Certificate in Mechanical Engineering (Machining): NQF Level 4 (MERSETA)
•	Etc etc.

**Comment by cchristelis** [comment]
Hi @lucernae, 

could you please update the look and feel of the bubble according to this request.

**Comment by cchristelis** [comment]
Hi @tmcbride1967, See my reformatting of your comment above, did I interpret your bold correctly? 

Zambli220 PTY LTD T/A POWDERMET (Atlantis) Site: **Atlantis**
John Vani Niekerk Street, Atlantis, 7349
Website: 
Phone:
Courses : 
•	National Certificate in Metal and Engineering Manufacturing Processes: **NQF Level 4** (MERSETA) <abbreviation only, not bold>
•	National Certificate in Mechanical Engineering (Machining): NQF Level 4 (MERSETA)
•	Etc etc.

**Comment by gubuntu** [comment]
screenshots from Tim's email showing more clearly the desired layout:

![screenshot from 2015-07-14 15 13 00](https://cloud.githubusercontent.com/assets/496911/8673952/019f2ea8-2a3b-11e5-8767-f3a88fa50c56.png)

![screenshot from 2015-07-14 15 14 53](https://cloud.githubusercontent.com/assets/496911/8673966/22bd1d16-2a3b-11e5-9210-b8f3aca397e2.png)

**Comment by gubuntu** [comment]
more from March:
>the pop up boxes are unclear (no labels against the fields and ugly,ugly, ugly.

**Comment by lucernae** [comment]
@cchristelis and @gubuntu I can manage to make it bold, but we have some problem with the data.

I think we need to standardize the data first. For example, I expect to fill:

**Campus: Athlone** with Athlone taken from the 'campus name', but the campus name itself is filled with data: 'Cnr of Protea & Eland Street Athlone 7764' , which is likely the address. Should I just take Athlone from the city name instead?

**Comment by gubuntu** [comment]
@lucernae please bold the whole field, don't extract the suburb in Django. It must be fixed in the database.
