### ISSUE TITLE
GPS co-ordinates

### ISSUE THREAD

**Issue by tmcbride1967** [kartoza/feti#108]
We need to correct a number of the provider locations. (drag and drop them where they are supposed to be). What is the mechanism for us (FETI) to do this?

**Comment by gubuntu** [comment]
This will be done in the admin area. The geometry (location) of the campus points will be (is) editable in a little dedicated online map.

**Comment by cchristelis** [comment]
Hi @tmcbride1967 and @gubuntu,
This is provided in the admin area. Please let me know who needs accounts. Then I will create the appropriate logins.

**Comment by cchristelis** [comment]
Hi @lucernae, I am assigning this to you as it falls under #81.

**Comment by cchristelis** [comment]
Hi @meomancer, we need this ability in the admin section.

**Comment by meomancer** [comment]
hello @cchristelis 
is it already handled by geoManager? i could change position of provider in admin section by drag point in map

**Comment by cchristelis** [comment]
@meomancer, this is for the provider backend.
