### ISSUE TITLE
403 on admin login

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#109]
I've just logged in as gavin, then logged out and cannot log in as gavin or March again as I now get a 

Forbidden (403)

CSRF verification failed. Request aborted.

Please fix and deploy on staging site asap. Admin functionality is imperative and has not been tested at all.

**Comment by lucernae** [comment]
Ok. I need to ask server credentials first to @timlinux or @cchristelis. Will do it ASAP.

**Comment by gubuntu** [comment]
@hvisage can you please set up @lucernae with access to kartoza3 asap?

**Comment by hvisage** [comment]
user rizky created with sudo rights

**Comment by hvisage** [comment]
Oh, checking it, which public key must be used??

**Comment by gubuntu** [comment]
server access details at https://github.com/kartoza/kartoza/wiki/Server-kartoza3

**Comment by cchristelis** [comment]
This is working on staging.
