### ISSUE TITLE
Error transforming geometry in django geoadmin

### ISSUE THREAD

**Issue by lucernae** [kartoza/feti#137]
From sentry:

> [u"Error transforming geometry from srid 'None' to srid '3857' (OGR failure.)"]

> Request repr(): unavailable

possible fix would be to install geospatial library in db postgis or in uwsgi container
> sudo apt-get install binutils libproj-dev gdal-bin

taken from https://docs.djangoproject.com/en/1.8/ref/contrib/gis/install/geolibs/

**Comment by cchristelis** [comment]
This is no longer relevant.
