### ISSUE TITLE
Non-superuser admin page.

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#15]
The non-superuser admin page should allow the logged in users to add/edit those tables that they have permissions for.

**Comment by gubuntu** [comment]
I don't think there is a requirement for this. Normal Django admin should be fine, perhaps with Grappelli. afaik, FETI staff will be the only admins and can be given edit rights to models by superuser. Users will have no admin access.

Superusers will be Kartoza staff and at least one nominated and trained person from FETI.
