### ISSUE TITLE
import etqa institutes as provided in Appendix.

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#16]
The etqa institutes have been listed and should be imported into the database.

See
- APPENDIX 1: ETQA TABLE VALUES (https://docs.google.com/document/d/1POLQ4pMvRa1FM81DBoGQwji1Ob4o7bwgc9YzSmVoWbw/edit?pli=1)

**Comment by gubuntu** [comment]
done by Admire's SQL and also available in MS Access DB
