### ISSUE TITLE
Wireframe search

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#163]
# Problem

We need to update the look and feel of the search page/landing page
# Proposed solution

Create a new landing page wire frame with updated search options.

**Comment by dimasciput** [comment]
Mockups from Maria :

![landing-page1](https://cloud.githubusercontent.com/assets/1979569/17362239/6c8692c2-599e-11e6-82ca-bb5125ec517e.jpg)
![landing-page2](https://cloud.githubusercontent.com/assets/1979569/17362240/6c8a773e-599e-11e6-9e6f-f0df9c8a3d65.jpg)
![landing-page3](https://cloud.githubusercontent.com/assets/1979569/17362241/6c8da06c-599e-11e6-8359-fa883328488a.jpg)
![landing-page4](https://cloud.githubusercontent.com/assets/1979569/17362242/6c903ac0-599e-11e6-8716-a64318ad0b84.jpg)
