### ISSUE TITLE
Create site colour pallette

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#167]
# Problem

The current blue on blue with the orange logo don't match well. 
# Proposed solution

Create a colour pallette to base our designs on.

**Comment by cchristelis** [comment]
![colours](https://cloud.githubusercontent.com/assets/2319504/16730098/2cba54a6-4771-11e6-9cc1-ba5bbac74dae.png)

**Comment by cchristelis** [comment]
@MariaSolovyeva, do you maybe have an update here? IIRC we where discussing blues and oranges.

**Comment by MariaSolovyeva** [comment]
Hello @all,

Yes it was an old one.
Here is the current version:

![feti-colors-21 09](https://cloud.githubusercontent.com/assets/10400420/18705683/cdab244e-7ff7-11e6-8688-1a39f4119ff4.png)

**Comment by dimasciput** [comment]
Added to wiki : https://github.com/kartoza/feti/wiki/Site-color-pallete
