### ISSUE TITLE
Implement landing page view in backbone

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#171]
# Task

We have a good idea of what the landing page will look like. Each of the major elements should be rendered by a backbone view. This way we can resize elements and let the map section take over the screen, when a search is done.

**Comment by cchristelis** [comment]
I'm thinking that @dimasciput should be working on this, but I think @meomancer you can give valuable inputs. And I think we should be borrowing some structure from FarmWeb.

**Comment by cchristelis** [comment]
![home3-expanded-where](https://cloud.githubusercontent.com/assets/2319504/17440217/0144b8b0-5b2c-11e6-92c3-096dd4a73e12.png)

**Comment by cchristelis** [comment]
When the user interacts with the map, the map takes full size of the screen. 
![map-results](https://cloud.githubusercontent.com/assets/2319504/17440516/31ee863e-5b2d-11e6-82eb-a6d247c98505.png)

**Comment by dimasciput** [comment]
@cchristelis so the search page is also in landing page?

**Comment by dimasciput** [comment]
@meomancer I created a branch to work on this issue https://github.com/kartoza/feti/tree/landing_page

**Comment by dimasciput** [comment]
Landing page with backbone is already implemented. Closing this issue.
