### ISSUE TITLE
Add search for provider in map view

### ISSUE THREAD

**Issue by dimasciput** [kartoza/feti#184]
# Problem

Currently the map view look like this

![screenshot from 2016-08-22 14 42 53](https://cloud.githubusercontent.com/assets/1979569/17847220/101ba1e8-6877-11e6-83c2-d14440440eef.png)
# Proposed solution

Add search bar 
![0144b8b0-5b2c-11e6-92c3-096dd4a73e12 1](https://cloud.githubusercontent.com/assets/1979569/17847198/f3643e16-6876-11e6-9f76-bd981ad72807.png)

**Comment by meomancer** [comment]
Closed #184  via #182
