### ISSUE TITLE
Let's encrypt

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#196]
# Problem

We may want to start using a user's location. For this we will need to be running https.
# Proposed solution

Setup let's encrypt.

**Comment by dimasciput** [comment]
I have been trying to get letsencrypt works in staging server with no avail. Here's what I have been done :
- Successfully obtained the letsencrypt certificates using webroot method https://certbot.eff.org/#ubuntutrusty-nginx
- The certificates are located in the host `/etc/letsencrypt/live/staging.feti.kartoza.com/`
- Created nginx conf file for ssl, located in `/home/web/feti/feti/deployment/ssl.feti.nginx.conf`
- Restart the nginx, open the site and all I got was this message "ERR_SSL_PROTOCOL_ERROR"

I was wondering if it has anything to do with the cloudflare settings ( https://support.cloudflare.com/hc/en-us/articles/200170566-Why-isn-t-SSL-working-for-my-site- ), or I just misconfigurate something. 

For now I set up feti staging server with no ssl.
@cchristelis please have a look at it. Thanks.
