### ISSUE TITLE
Spacial search 2

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#206]
# Task

Allow users to select a point and a buffer radius. This will feed into the search results.

**Comment by dimasciput** [comment]
Hi @cchristelis, is something like this would be good enough? 
![anim](https://cloud.githubusercontent.com/assets/1979569/18263642/e1289f92-7435-11e6-97c5-4631e4bdc6f7.gif)

**Comment by cchristelis** [comment]
@dimasciput, yes this is good.
