### ISSUE TITLE
Admin section

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#222]
# Problem

Some important fields are not yet editable.
# Proposed solution
- [x] A user should be able to update the Primary Institute website. (Question: should users be assigned to these PIs?)
- [ ] A user should be able to update the campus address.

**Comment by meomancer** [comment]
For Primary Institue Admin
- [x] Added relation user and primary institue
- [x] Added primary institute list in admin section
- [x] Primary institute admin can edit fully of it's campus

For Campus Admin
- [ ]  Allowed to edit campus address
