### ISSUE TITLE
Scraping

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#246]
# Problem

Currently the API's for the courses and campuses offered by the saqa site: http://regqs.saqa.org.za/search.php and the occupations offered by the ncap site:
http://ncap.careerhelp.org.za/occupations
are not available. So until this is available we can only access this data through the page.
# Proposed solution

Let's build a management command that scrapes campuses and courses and their connections from saqa. And a management command that scrapes occupations, learning pathways and the courses.

Perhaps have a look at https://www.crummy.com/software/BeautifulSoup/bs4/doc/

**Comment by cchristelis** [comment]
@meomancer, based on our discussion earlier, does this ticket make sense to you?

**Comment by meomancer** [comment]
@cchristelis 
yes, it make sense
one question is

http://ncap.careerhelp.org.za/learningpathway/08b0659b-c050-4a6c-8cce-637232da50fb

on pathway 1
step 1 : National Senior Certificate - Diploma Entrance or National Certificate (Vocational) is general course but on 
step 2 : Diploma/Higher Diploma in Accounting (NQF Level 6) , it is just provided by the provider in the list?

so, where the course for general course should be provided? it is just like none of registered provider provides it now?

**Comment by cchristelis** [comment]
There will be courses that are not currently being provided by any provider. This usually happens because courses are added and dropped all the time. In our interface we won't show any link to providers and perhaps even hide this pathway. The link between the pathways and the courses need to still remain, in case a university starts offering the course again.

**Comment by dimasciput** [comment]
Hi @meomancer , could you update the wiki page with a guide how to scrape campuses and courses?

**Comment by meomancer** [comment]
https://github.com/kartoza/feti/wiki/Working-with-Scraping-Database
