### ISSUE TITLE
User profile and user area

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#247]
# Problem

We currently have the concept of a front end user who is assigned to campuses from an administrative point of view. We don't have a user, who can self register and use the site from a learner perspective. 
# Proposed solution

Create a user profile model. In this we need to capture the users's location. Allow users to register and login using their social media accounts.

**Comment by cchristelis** [comment]
@dimasciput, please also make a suggestion to other fields that would be relevant to the user profile.

**Comment by dimasciput** [comment]
I think user can also save their search results.
