### ISSUE TITLE
Update search results view

### ISSUE THREAD

**Issue by dimasciput** [kartoza/feti#255]
Current search result view : 

![improve the search result](https://cloud.githubusercontent.com/assets/1979569/18628338/f06c7e34-7e89-11e6-8c0e-fdc0fad21806.png)

I think we can improve the search results to match the theme.

**Comment by MariaSolovyeva** [comment]
Here is the design of possible search results. Is there any discussion about it anywhere?
![map-results](https://cloud.githubusercontent.com/assets/10400420/18704794/1659f066-7ff4-11e6-9655-8c8972dcb712.png)

**Comment by meomancer** [comment]
Ah, yes, I remember the design now
Could you update the css, @MariaSolovyeva 
that i could update script for "63 Providers in Northern Cape" title?
