### ISSUE TITLE
Update institute and provider list view

### ISSUE THREAD

**Issue by dimasciput** [kartoza/feti#256]
Current view:

![1](https://cloud.githubusercontent.com/assets/1979569/18628387/30634540-7e8a-11e6-9333-a1de0f95f538.png)
![2](https://cloud.githubusercontent.com/assets/1979569/18628389/30919bb6-7e8a-11e6-8ca5-4dee3302ed06.png)

Update this view to match our current theme.

**Comment by MariaSolovyeva** [comment]
Hello there, 
I created the image placeholders, same as in the search results, what do you think of this?
What is the difference between Primary Institutes and Providers?

![admin](https://cloud.githubusercontent.com/assets/10400420/18708441/77c64048-8003-11e6-89ff-e24e3adeb568.png)

**Comment by meomancer** [comment]
@MariaSolovyeva 
thank you maria
could you update the css and html?
If you have problem, you could ask me

The different is primary institution is a like main institution, and providers is the actual campus that can be in different place.
