### ISSUE TITLE
Update Partner Section

### ISSUE THREAD

**Issue by meomancer** [kartoza/feti#262]
# Problem

We need add partner logos. 

# Proposed solution 

- IPSS Logo
- Western Cape Education Department (http://sijonga-phambili.org/wp-content/uploads/2012/10/WCED-Logo-2012-2.jpg)
- SAQA http://www.saqa.org.za/images/saqa.jpg
- Ford Foundation
- Kartoza

**Comment by cchristelis** [comment]
![4c3bff4c-3b0a-11e5-9e25-b70eae67cd54](https://cloud.githubusercontent.com/assets/2319504/20652597/cc59b9ec-b504-11e6-81ac-52ab54fabe92.jpg)

**Comment by dimasciput** [comment]
![screenshot from 2016-11-28 10 41 03](https://cloud.githubusercontent.com/assets/1979569/20655656/33faa104-b557-11e6-9829-6b24ccfecf13.png)

@cchristelis , it doesn't look good if I put the logo in the top left header.

**Comment by cchristelis** [comment]
also please add https://upload.wikimedia.org/wikipedia/commons/b/b3/Logo_of_the_Ford_Foundation.png into the partner section, since they are funding this.
