### ISSUE TITLE
Supports mobile user

### ISSUE THREAD

**Issue by dimasciput** [kartoza/feti#288]
# Problem

Opening website in mobile device will look awful.
# Proposed solution

Update the layout and supports mobile view.

**Comment by meomancer** [comment]
i have idea
instead still showing topbar, we could use navigation bar feature from android like
like google maps, so there is not much space that is spent just for navbar

**Comment by cchristelis** [comment]
@meomancer, that is a nice idea.

**Comment by cchristelis** [comment]
FYI @carina1000
