### ISSUE TITLE
Populated map on load

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#329]
# Problem

When the map is loaded the first time, it seems very empty.

# Proposed solution

Show all results on load.

**Comment by dimasciput** [comment]
If we populated all campus on landing page, there will be a lot of campus and it will be slow, also it doesn't look good.

![screen shot 2016-12-06 at 11 15 58 am](https://cloud.githubusercontent.com/assets/1979569/20912863/7e755090-bba5-11e6-82c2-22a290104c72.png)

**Comment by meomancer** [comment]
@dimasciput i think we could use marker cluster?
https://github.com/kartoza/feti/issues/185

**Comment by meomancer** [comment]
hi @cchristelis 
it seems that our data is too big, which is 1229, and also there is serializer to get course. This will take long time to get all result. Also i tried to make cache file for all result so just download this file, but the file has 130MB size.

So i have a purpose to make pagination for feti? Maybe not alphabet pagination but by scroll pagination?

**Comment by meomancer** [comment]
as per disscussion, we reduce informations by not getting course when search it. Course is shown when user expand campus and it will call ajax to get it's courses.

this will also fix #342
