### ISSUE TITLE
Geocoding script

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#33]
We need a geocoding script to locate campuses based on their addresses. This can later be incorporated as a management command.

**Comment by cchristelis** [comment]
Hi @Gustry,

for now all we need is a general geocoding script.
@gubuntu, could you please point Etienne, to the preferred api?

**Comment by gubuntu** [comment]
I gather this is considered done. Is the script in this repo? Did it do 1Map with fallback to Google?

**Comment by cchristelis** [comment]
Yes, it is 1Map with Google fallback. @Gustry is busy finishing the import script.
