### ISSUE TITLE
User name with dashes causes 404 when going to user profile

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#336]
# Problem

When users sign in with '-' in their name (please check other special characters as well) the profile page gives a 404.

# Proposed solution

We could either constrain the users when signing up or make the regex in the url more permissive. I think allowing '-' is fine, but we definitely want to stay away from other special characters...

**Comment by dimasciput** [comment]
I don't think username with dash is common, I think I'd rather create a constrain ( no special character for username ).

**Comment by cchristelis** [comment]
@dimasciput, agreed, let's then add that to the signup validation.
