### ISSUE TITLE
favourites/saved/bookmarks

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#338]
# Problem

The terminology between favourite and saved is inconsistent. Also unfavoured sounds a bit weird.

# Proposed solution

Let's make the labels consistent I would propose either `favourite` or `bookmark`. Also let's rather `remove from favourite` than `unfavourite`. 

@marchturnbull, do you have a preference between `favourites` and `bookmarks` for 'saved courses'?

**Comment by marchturnbull** [comment]
i think 'favourites' sounds positive....
