### ISSUE TITLE
Boundaries are not suitable for our regional approach

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#340]
# Problem

We are focusing on the western cape, as such country and province level is not applicable.

# Proposed solution

Let's make the starting level be at region then drill down to municipal.

**Comment by cchristelis** [comment]
@NyakudyaA, could you provide us with the regional data for the western cape and then hand this ticket on to @dimasciput.

**Comment by NyakudyaA** [comment]
[wc_data.zip](https://github.com/kartoza/feti/files/633943/wc_data.zip) @dimasciput  here are the files. I have provided you with sql dumps you can load them directly to the db or a sqlite database where you can see the files in QGIS first.

**Comment by dimasciput** [comment]
Hi @NyakudyaA can you provide me the shp file instead? I'm having a hard time to restore sql to the db because they have different schema with country and province table.

**Comment by NyakudyaA** [comment]
@dimasciput you can connect the sqlite database to QGIS and save the layers as shapefiles. [http://docs.qgis.org/2.0/en/docs/training_manual/databases/spatialite.html](url) . I will prepare them and send them.

**Comment by NyakudyaA** [comment]
[western.zip](https://github.com/kartoza/feti/files/635922/western.zip)  Here are the shapefiles. they are already projected to 3857

**Comment by dimasciput** [comment]
Thanks @NyakudyaA !

**Comment by meomancer** [comment]
duplicated with #265
