### ISSUE TITLE
Kartoza partners logo

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#345]
# Problem

The kartoza logo looks a little unbalanced next to the ford foundation logo. 

# Proposed solution 

Use a horizontal logo see: https://drive.google.com/drive/u/0/folders/0B8Vft3QRhetbNXFGU01LYThlYzA

**Comment by meomancer** [comment]
@cchristelis 
could you copy the image in here? i can't access the link

**Comment by cchristelis** [comment]
![kartozalogohorizontalrgb-320x132](https://cloud.githubusercontent.com/assets/2319504/20960060/28b31c74-bc67-11e6-9536-63b57986497e.png)
