### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#350]
# Problem

We need to use the advanced search option.

# Proposed solution

Add:

- Field of study
- Subfield of study
- Qualification type
- Minimum Credits
- NQF level

**Comment by cchristelis** [comment]
@marchturnbull, when we get the NQF entry level table, we can add that as well.

**Comment by cchristelis** [comment]
On hover we should have an explanation for each of these terms.

**Comment by MariaSolovyeva** [comment]
Hi @cchristelis , is it a separate page or sort of dropdown?

**Comment by cchristelis** [comment]
@MariaSolovyeva, so the search should be expandable to an advanced search. perhaps another row, or perhaps we make the search box thinner and add it to the left?

**Comment by dimasciput** [comment]
Hi @MariaSolovyeva , what is the status for this? Thanks.

**Comment by MariaSolovyeva** [comment]
Hi @cchristelis  and @dimasciput , here is the design
![advanced_search](https://cloud.githubusercontent.com/assets/10400420/22965649/9ea0377a-f36f-11e6-94b1-cbdc874b323c.png)
![advanced_search_open](https://cloud.githubusercontent.com/assets/10400420/22965654/a169cfd4-f36f-11e6-85ff-d4897d4169c7.png)
