### ISSUE TITLE
Search results must include Campus names

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#354]
Problem:
Search results for providers show only the Primary Institutions, not the campus names.  This is a problem where the results include two campuses from the same 1ary Inst. but in differentlocations.

Solution:
Please return the Provider (Campus) name in the search Resutls with the 1ary Institution.  e.g. Northlink College, Belhar Campus

**Comment by cchristelis** [comment]
I think this is because we only show the first certain number of characters. It is related to #361.
