### ISSUE TITLE
Fuzzy search is too fuzzy

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#355]
Problem:
If you search for Bellville in Where to Study, I get far too many unrelated results

**Comment by dimasciput** [comment]
Latest update, 

Search for Bellville returns 5 campuses

<img width="1234" alt="screen shot 2017-02-26 at 1 38 45 pm" src="https://cloud.githubusercontent.com/assets/1979569/23337704/f7e099bc-fc28-11e6-9dbb-c43f67bf1324.png">
