### ISSUE TITLE
Public vs Private institution

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#359]
Problem:
In FORD1 there was an important visual distinction between Public and Private institutions.  

1) there was a legend on the map
2) markers were different
3) it is very important to users
4) it was a primary selection criterion

Have we lost the ability to do this because we have brought data in from the national dbase?

Possible Solution:

If we no longer have this data, we need to add a field in the Provider table so that each record can be flagged public or private.  default value at this stage = 0

We will then populate this field ourselves using value = 1 for public institutions - that list is shorter and more easily acquired.

In the future:  When a new Provider is created this field must be mandatory with no an invalid NULL default value, to force users to populate it

**Comment by cchristelis** [comment]
I think we will have to rely on admin staff editing this. And re-add the icons and legend.

**Comment by cchristelis** [comment]
@ann26, please use the blue icon for public institutes and the red one for private. Please include a legend.
