### ISSUE TITLE
Fuzzy search results

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#36]
The search is quite powerful. But also this causes issues when a user tries to search for something and he misspells. This may leave a 0 results page, which is quite frustrating. Increasing the fuzziness of the search results may assist here.

**Comment by lucernae** [comment]
I did some research on elastic and haystack backend's source code. This is what I got:

- Elasticsearch Backend uses query_string query, this article has some nice information: [Query-String Query](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html)
- We had a fuzziness settings! In Query-String Query and it seems it already sets in auto [Fuzziness](http://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#fuzziness). We already had some fuzziness search, but maybe we should increase it based on the terms length.
- And this is for a bookmark: [Custom Backend](https://www.wellfireinteractive.com/blog/custom-haystack-elasticsearch-backend/)

**Comment by lucernae** [comment]
On second thought, the maximum allowed fuzziness is 2 :(. Except if we uses Fuzzy Like This Query

**Comment by lucernae** [comment]
Fuzzy Like This Query sucks if we uses more than one terms :(

**Comment by cchristelis** [comment]
Searching for multiple terms across Campuses and Courses should be supported. Due to time constraints this will have to enjoy low priority for now.

**Comment by gubuntu** [comment]
Ajax returning possible values from search fields as user types, is another option.

**Comment by gubuntu** [comment]
Searching on multiple fields is a core requirement.  Comment from March on 30 May: "The search methodology is still not sophisticated enough.  the client needs to be able to search using multiple keywords, which search multiple fields.   This seems to have gone backwards since my search for 'engineering' only produces results where 'engineering'  is in the provider name, not the course.  thus the universities are excluded."

**Comment by gubuntu** [comment]
moving discussion to #48. This is high priority.
