### ISSUE TITLE
Highlight peculiarities

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#361]
# Problem

When searching for `Cape Town`, the words cape town are highlighted in all the wrong places.

# Proposed solution

Investigate and fix.
<img width="1154" alt="screen shot 2016-12-08 at 8 43 13 pm" src="https://cloud.githubusercontent.com/assets/2319504/21024086/e3d14326-bd8b-11e6-8584-d9337000cd6d.png">

**Comment by dimasciput** [comment]
Hi @cchristelis , I see that cape town highlighted in the results list.
