### ISSUE TITLE
save all administrative to geojson file

### ISSUE THREAD

**Issue by meomancer** [kartoza/feti#366]
# Problem

We need a fast administrative call, but some of administrative that has dense polygon, it take a lot of time

# Solution
Save it as cache geojson file to return it fast

**Comment by cchristelis** [comment]
@meomancer, I think a better solution is to simplify the polygon.

**Comment by cchristelis** [comment]
Perhaps you could get advice from @Gustry on how this is normally done.

**Comment by meomancer** [comment]
duplicated with #380
