### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#367]
# Problem

When results get big, things get slow.

# Proposed solution 
Strip down amount of information that we download on a request.

**Comment by meomancer** [comment]
optiomasion:

- [ ] we reduce informations by not getting course when search it. Course is shown when user expand campus and it will call ajax to get it's courses.

**Comment by cchristelis** [comment]
Only transfer campus name and id as well as course id's first. Then download data needed for popup when user opens popup and populate course details when user expands course.

**Comment by cchristelis** [comment]
Identify expensive joins.

**Comment by cchristelis** [comment]
@meomancer, please add some times to requests, searches, joins, lookups.

**Comment by cchristelis** [comment]
and then we discuss this when we see the timestamps.
