### ISSUE TITLE
Search results not being kept in the search box. 

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#37]
Since the search is very central in this application and the current page state hinges on that:
 - [ ] keep those terms in the current search box
 - [ ] have button to reset / restart search
 - [ ] add search string to url (RESTful) so it can be bookmarked and shared (in spec c iv)

**Comment by lucernae** [comment]
Does the current app can already do this?

**Comment by gubuntu** [comment]
have a look at http://feti.kartoza.com

**Comment by lucernae** [comment]
@gubuntu the search terms still in the search box. Perhaps what we want is having it on the address box? so we can have a search link that we can bookmark?

**Comment by gubuntu** [comment]
On 13/05/2015 08:33, Rizky Maulana Nugraha wrote:
>
> @gubuntu <https://github.com/gubuntu> the search terms still in the
> search box. Perhaps what we want is having it on the address box? so
> we can have a search link that we can bookmark?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kartoza/feti/issues/37#issuecomment-101531399>.
>
you mean in the url? Yes that makes sense.

-- 
------------------------------------------------------------------------------------------
Gavin Fleming Joint MD PrGISc [PGP1234]
Visit http://kartoza.com <http://kartoza.com/>to find out about open source:
* Desktop GIS programming services
* Geospatial web development
* GIS Training
* Consulting Services
Skype: phlemingo
-------------------------------------------------------------------------------------------
Kartoza = Linfiniti ∪ Afrispatial

**Comment by cchristelis** [comment]
Hi @lucernae, although this is working it has caused issues #57 and #58... I will close this and follow up the progress of those in the individual tickets.
