### ISSUE TITLE
Where to Study, inconsistent treatment of search results

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#385]
Problem:
Search for "University Cape Town" and a single result is found.  No slide-out bar is displayed on the right so the user cannot interrogate the courses offered.

Contrast with search for "university" which yields 9 results, all of which are displayed in the slide-out, and each can be expanded

[Incidentally - there are three Universities in Cape Town - should we discuss the search methodology?]

**Comment by dimasciput** [comment]
Update for latest version : 

Search for "University cape town" returns 3 campuses 
<img width="1235" alt="screen shot 2017-02-26 at 1 35 39 pm" src="https://cloud.githubusercontent.com/assets/1979569/23337683/8c89cd32-fc28-11e6-8a92-6c04bb8751cb.png">

Search for "University" returns  26 campuses
<img width="1248" alt="screen shot 2017-02-26 at 1 36 54 pm" src="https://cloud.githubusercontent.com/assets/1979569/23337690/ac72984a-fc28-11e6-8701-bc9b9c17430b.png">

Is this better @marchturnbull ?
