### ISSUE TITLE
"Saved" function not working

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#386]
Problem:

User 'admin_usr' has had several courses / providers added to favourites by me.  

1.  the newly added items are not showing

2.  The page element never completes loading 

3.  Cannot interrogate existing saved courses (possibly because of the above)

4.  possible duplication of courses that are already saved

**Comment by dimasciput** [comment]
It's working now in staging.
https://staging.feti.kartoza.com/#
Fixed by https://github.com/kartoza/feti/pull/383
