### ISSUE TITLE
Turn this into a single page app

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#39]
Currently we have 3 pages. The search and results, the login and the admin page(s). I would be great if the user experience could all happen from the front page. This would imply, Removing the find link. Changing the login page and to an ajax query hovering over the page.

**Comment by cchristelis** [comment]
Hi @lucernae, this should include the point 4 that we spoke about as well. That is the user adding and editing of campuses and courses.

**Comment by gubuntu** [comment]
All editing is now to take place in fully configured Django Admin rather than user forms, right? Please elaborate since this isn't clear from current functionality and Django Admin would be the quickest way to meet the brief. 

Bear this navigation feedback from March in mind while implementing:
>A user who is amending details of courses / providers will naturally want to toggle between the admin area (without loggin out) and the search area to ensure changes have taken correctly etc.

**Comment by cchristelis** [comment]
We will be using django admin for the foreseeable future. Hence this issue is no longer relevant.
