### ISSUE TITLE
Geographical search tools not working on What to study page

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#401]
Problem:
when a search has been done on the What to Study page the following tools do not work

- provincial selection

- polygon  selection

**Comment by dimasciput** [comment]
Hi @marchturnbull , please do hard refresh and check the site again. Thanks.

**Comment by cchristelis** [comment]
@dimasciput, when updating resources, please append a '?' and a random number or a serial number, to force a resource re-download.

**Comment by dimasciput** [comment]
@cchristelis But we are using require js, if the js name changes then it wouldn't be recognized, it seems we need to do more than that.

**Comment by dimasciput** [comment]
Probably using this library https://github.com/etianen/django-require, but then I think it wouldn't integrate nicely with Pipeline.

**Comment by dimasciput** [comment]
Geographical search tools is working.
