### ISSUE TITLE
Geographical boundary search does not reset when new search initiated

### ISSUE THREAD

**Issue by marchturnbull** [kartoza/feti#402]
Problem:
If a geographical search (boundary) is done eg in the Where to study screen, that search filter is maintained if you start a new search in the What to Study screen

ALSO - the boundary search does not work most of the time

**Comment by dimasciput** [comment]
> Problem:
If a geographical search (boundary) is done eg in the Where to study screen, that search filter is maintained if you start a new search in the What to Study screen

That was actually intended, but we can change it in the future if you want different layer filter on each category.
