### ISSUE TITLE
Handle results

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#41]
Refer to spec 3c i-iv

The results of a search must:
 - [x] appear in the RH panel, alphabetical order showing Providers incl campuses. 
 - [x] appear in detailed list with courses that meet search criteria as in http://pi.mapaproject.org/, with same fields as popups (Gavin thinks all available info about a course should be returned -- i.e. all fields and lookups)
 - [x] if multiple courses per provider are returned, the provider itself must only appear once (slight modification of c i)
 - [x] download pdf of search results (as they appear below the map) (#67)
 - [ ] --optional nice to have -- A email results link could be quite useful. Adding an email option can be achieved by simply sending a search query with the currently entered search terms.

**Comment by lucernae** [comment]
Which spec document is this from?

**Comment by gubuntu** [comment]
The only one - March's Google Doc

**Comment by lucernae** [comment]
we don't have pdf result yet.
