### ISSUE TITLE
Default icon is bad

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#440]
# Problem

The default icon is that of a specific University.

# Proposed solution

Perhaps use the DEDAT icon as a default?

**Comment by cchristelis** [comment]
Use: https://thenounproject.com/term/authorization/542379/

**Comment by dimasciput** [comment]
@cchristelis 
I created default icon 
![default-provider-logo](https://cloud.githubusercontent.com/assets/1979569/24835716/29a5089a-1d33-11e7-9179-87e8eaef5aa2.png)

![screen shot 2017-04-09 at 2 45 29 pm](https://cloud.githubusercontent.com/assets/1979569/24835719/37180a72-1d33-11e7-80a7-cef7a99b93c1.png)
