### ISSUE TITLE
facebook share

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#447]
We want this.

**Comment by cchristelis** [comment]
We need a facebook profile.

**Comment by cchristelis** [comment]
The Facebook share does not work as expected. All other shares share the current URL. In other words when using twitter share etc. The users are able to get to exactly the same result as where they came from. This is not the case with the facebook share and should be updated to use the current url.

**Comment by myarjunar** [comment]
@cchristelis did you try to actually share the link on your Facebook and then click on the shared link? I've tried it and it works fine..
![fb_sharer](https://user-images.githubusercontent.com/11134669/43300819-82b9fd8c-918b-11e8-8e1d-e8b621048e6f.gif)

**Comment by Vries14** [comment]
Shared on Facebook. Clicked on link on my timeline and got redirected to the same results of my search.
