### ISSUE TITLE
Always Clear

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#450]
# Problem

When I move between tabs it remembers the previous search results. This should always clear. I.e. when we move between tabs we always land on a clear search.

**Comment by dimasciput** [comment]
Well this is easier to implement, but are you sure you want this behavior? I thought we want tabs like browser tab.

**Comment by cchristelis** [comment]
@dimasciput, yes @MarchTurnbull and I had a chat today. Basically there is too much weirdness that happens when moving between tabs.
