### ISSUE TITLE
All filters in text

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#452]
# Problem

When I do an area search the criteria for this search is given in the results. It would be great if the same behaviour was also followed with other search items (such as advanced search.

# Proposed Solution

Update​ the search results string above the search results to contain the search criteria.

**Comment by dimasciput** [comment]
@euclidian, the layout becomes weird, please fix it
<img width="1430" alt="screen shot 2017-04-05 at 3 06 14 pm" src="https://cloud.githubusercontent.com/assets/1979569/24695897/d87b70f4-1a11-11e7-9210-b66c630ca524.png">
