### ISSUE TITLE
Load most recent data

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#47]
- [x] Update / merge spreadsheet and MS Access database and load into PostgreSQL such that the FETI database is fully populated with all available course, provider and lookup table data. As clean as possible, no duplicates, etc.
 - [x] load geocoding results and update campus geometry column with them. 
 - [ ] test and confirm acceptance by FETI, than back up and use for deployment. 

Thereafter, all data maintenance will happen on the live database via the admin functions of the website or via other backend db clients.

**Comment by cchristelis** [comment]
The third point is followed up in other tickets according to @Gustry.
