### ISSUE TITLE
extending API

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#503]
# Problem

The API needs to be reviewed to a point where it is fully pluggable.

# Proposed Solution

Investigate which API views are missing and add them.

**Comment by anitanh** [comment]
The API for occupation does not work, also please create an API to call occupation by the name.

**Comment by anitanh** [comment]
Sorry! The API for occupation does work, we just need to call it with query, i.e. `http://0.0.0.0:63102/api/occupation?q=electrician` 
Sorry my bad :(

**Comment by meomancer** [comment]
hi @sonlinux 
i'm not sure the purpose of the API that just return all
my suggestion is maybe API can be filtering by some field
or maybe you could change url using
```
api/national_graduate-school_in_education/all
```
because in my mind, API can be filtering, not just return all data, because it will not be usable
