### ISSUE TITLE
Integrate API into Game Changer page

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#504]
# Problem

We would to demonstrate the API being used on another site.

# Proposed Solution 

Integrate this in http://careers.wcappsdev.co.za/ showing locations of campuses using the current embed maps and linking to courses and career searches.

**Comment by anitanh** [comment]
How about this @cchristelis ?

gif:
![peek 2017-10-17 08-18](https://user-images.githubusercontent.com/26101337/31642196-e78ce8e8-b313-11e7-9e08-aa3cacfa41f1.gif)

static:
![screencap](https://user-images.githubusercontent.com/26101337/31642254-3a1e1546-b314-11e7-8ac4-93bd8e9c9a1f.png)
