### ISSUE TITLE
Update Landing Page Banner Wording

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#523]
# Problem

Currently we are getting the same text with various counts. We would like to use this to be more informative.

# Proposed Solution

Change the text to something better.

**Comment by cchristelis** [comment]
# New Proposed Solution

Let the page start out with the map expanded. [Remove the banner and the sponsors]

**Comment by cchristelis** [comment]
the height of the new map is not correct let the landing page be exactly equal to the where to study page. i.e. also remove the bottom footer...

**Comment by cchristelis** [comment]
@ann26, this change seems to have been undone:
![Screen Shot 2018-07-26 at 12.57.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba461b7953d2fd0f723be1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f56b7191a379ed0c2e56415a47bc30254d58eeb9cb74fce36f34985619e8d66c5a22946917fdea874bba50bf728b4e80b4b48b4dc1fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e34853a7123664ef703e6e0a.png)

**Comment by anitanh** [comment]
hi @cchristelis , I have removed them. this is the view from testing site:
![screenshot from 2018-07-26 09-30-29](https://user-images.githubusercontent.com/26101337/43238022-8cde8f6a-90b6-11e8-8854-7b03237feb81.png)
