### ISSUE TITLE
Results below map.

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#54]
Please add a list of results below the main map. These should be an expanded version of the list on the right.

**Comment by gubuntu** [comment]
Gavin: These expanded results below the map should have two views, controlled by a radio button
- Providers (default)
- Providers and all available courses
The chosen view should feed directly into any share functionality (url, pdf #67)

interpreted from March:
>This [handling courses in search results] is currently being handled differently to the manner anticipated:  an unexpanded list of results is the default view (i.e. just Providers) and they can be expanded individually to show the individual courses.
This is effective but will need to be further addressed in the SHARE functionality.  
Within the SHARE function there is a requirement for a PDF report of a Search.  
My suggestion is that this PDF function will need to offer the User options of ‘List Providers only’ and ‘List Providers and All Available Courses’

**Comment by cchristelis** [comment]
@gubuntu, we could handle all of this by providing two pdf download options, since the required difference is only at the pdf level. Rather than having 2 widgets, a button and a radio button controlling the download at the button, we could have a download pdf summary, download full pdf report.

**Comment by gubuntu** [comment]
sounds good

**Comment by cchristelis** [comment]
This is implemented in PR #118.
