### ISSUE TITLE
Campus icons not found (404)

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/feti#562]
### Problem
38 campus icons are not found.
![capture d ecran 2018-07-04 a 14 59 34](https://user-images.githubusercontent.com/35932320/42278430-15fdfdd0-7f9b-11e8-99de-fad170a82200.png)

Live example: http://159.69.42.250:63100/

### Proposed solution
Find the icons.

**Comment by cchristelis** [comment]
This is high priority please resolve.

**Comment by cchristelis** [comment]
@meomancer, could you do an rsync between the servers, please.
