### ISSUE TITLE
Updating user profile does not work

### ISSUE THREAD

**Issue by pierrealixt** [kartoza/feti#563]
### Problem

Updating a profile does not update the database.
![feti-update-profile](https://user-images.githubusercontent.com/35932320/42279510-46f186c0-7f9e-11e8-9946-2dda1dec6465.gif)

Logs:
```
Error creating geometry from value '' (String or unicode input unrecognized as WKT EWKT, and HEXEWKB.)
django.contrib.gis ERROR widgets.py L45: Error creating geometry from value '' (String or unicode input unrecognized as WKT EWKT, and HEXEWKB.)
[04/Jul/2018 15:29:13] "POST /profile/update/31 HTTP/1.1" 200 3486
```

**Comment by cchristelis** [comment]
On staging i get the following error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
OpenStreetMapSSL.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
OLMapWidget.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
31:139 Uncaught ReferenceError: OpenLayers is not defined
    at 31:139
31:317 Uncaught TypeError: Cannot read property 'map' of undefined
    at 31:317
```
no map appears.

**Comment by cchristelis** [comment]
![Screen Shot 2018-07-26 at 9.35.08 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba461b7953d2fd0f723be1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246456f56b7191a371f1112e4f5f575ecc3c4a4356bcbbd671f3e57862804e0eead0680926923b40febdd61aee04e8208a4a87bebd8b4dd2f42f67b6d5db1063474f4dcbed5727a19e41c95df549e74e52a7113762e4712431.png)

**Comment by Vries14** [comment]
In the profile update there is an option to update the bio.  When updating the bio and submitting it, the bio information does not show when viewing your profile.

**Comment by Vries14** [comment]
User profile is able to update with new information.  Location can be set through the use of the map and can be viewed in profile.
