### ISSUE TITLE
Pins are not updated on spatial queries (without search terms)

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#569]
# Problem

When I make a spatial query (circle) the panel on the right updates, but all pins are still visible.

# Proposed Solution

make sure the update map is called, even without a search term.

**Comment by cchristelis** [comment]
This is an issue on  http://159.69.42.250:63100

**Comment by myarjunar** [comment]
can't replicate both on staging and my local machine. no other location is visible other than the one in the circle. here is what I got
![circle_radius_pin](https://user-images.githubusercontent.com/11134669/43120081-2862a716-8f43-11e8-9eec-bfacf2fd4703.gif)

If I understand it incorrectly, please let me know @cchristelis

**Comment by myarjunar** [comment]
can we close this ticket @cchristelis ? It seems like the behavior is already correct

**Comment by cchristelis** [comment]
CNR either
