### ISSUE TITLE
Pathway didn't work

### ISSUE THREAD

**Issue by myarjunar** [kartoza/feti#573]
when the user chooses pathway other than pathway number 1, the pathway didn't show anything, only a loading icon.

**Comment by myarjunar** [comment]
how to replicate:
- only works on 1 page refresh cycle.
- if it works at the first time, then you choose `what to study` tab, and then back to occupation tab again and perform a search on occupation, then pathway other than number 1 will not be loaded

**Comment by cchristelis** [comment]
working on staging.
