### ISSUE TITLE
Sharing Favourites and Spatial Searches

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#574]
# Problem

The favourates and spatial searches are not sharable.

# Proposed Solution

Allways have the share tools available.

**Comment by pierrealixt** [comment]
I think that issue is close to the one I'm working on: #527

**Comment by anitanh** [comment]
hi @pierrealixt , are you planning to include the fix for this issue on your upcoming PR?

**Comment by pierrealixt** [comment]
Yes I think so.

**Comment by anitanh** [comment]
@pierrealixt ok cool
