### ISSUE TITLE
occupation detail layout

### ISSUE THREAD

**Issue by myarjunar** [kartoza/feti#594]
occupation detail left a gap on the bottom. I thought it was not intentional and would be better to fix it.
![selection_245](https://user-images.githubusercontent.com/11134669/43144986-90c584c8-8f88-11e8-96a3-aad99f20fd91.png)

**Comment by cchristelis** [comment]
could you estimate how long you think this will take, please @myarjunar

**Comment by myarjunar** [comment]
after I saw the code, it seems like @ann26 did it on purpose. May I know is there any reasons why did you change it from `height: 90%` to `height: 100%`? If it was indeed intended, then we should just close this ticket.

**Comment by cchristelis** [comment]
yeah, I think we can close it.
