### ISSUE TITLE
details bug

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#610]
# Bug Report

1. Click on Choose Occpuation tab
2. Click on details under Abrasive Wheel Maker
3. Click on details under Accounts Clerk

# Error Condition

The occupation details don't update. Although the arrow indicates that we are now at accountants clerk we still see the details of abrasive wheel maker.

**Comment by myarjunar** [comment]
please look at issue #604  for more detail

**Comment by Vries14** [comment]
Checked to see if details are updating  when you are clicking from one occupation to another.
