### ISSUE TITLE
Map Map Map

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#618]
# Bug

The map does not appear when I try and edit my profile:
- https://ford2.kartoza.co.za/profile/update/XXX
nor when I try and update the location of a campus:
https://ford2.kartoza.co.za/provider/1506/update/

I get the following error on the console:
```
Uncaught ReferenceError: OpenLayers is not defined
    at 29:139
29:322 Uncaught TypeError: Cannot read property 'map' of undefined
    at 29:322
```
and
```
Uncaught ReferenceError: OpenLayers is not defined
    at OLMapWidget.js:6
    at OLMapWidget.js:376
(index):107 Uncaught ReferenceError: OpenLayers is not defined
    at (index):107
```
Which I think are import errors.

**Comment by anitanh** [comment]
Hi @cchristelis it is already fixed here: https://github.com/kartoza/feti/pull/617
