### ISSUE TITLE
Create a PDF with the current search results and map

### ISSUE THREAD

**Issue by cchristelis** [kartoza/feti#67]
# Outline

We need to allow the user to share the current results as a printable PDF. The format of the PDF is slightly different to the on screen version and hence a custom pdf should be generated.
# Proposed solution

All the information required is already on the client side. It is hard to recreate the same map on the server. Therefore I suggest that we use a client side pdf generation tool.

(Also in #41)

**Comment by gubuntu** [comment]
Use existing approach and code where possible, no time or budget for investigation. Consider Kartoza's Farminfo approach using wkhtmltopdf, or https://docs.djangoproject.com/en/1.8/howto/outputting-pdf/. 

Also first generate a pdf without a map. The map is a nice-to-have that must not hold up pdf generation.

**Comment by gubuntu** [comment]
Do this before #67. Since most info can be viewed in the current layout, we await feedback from the client as to whether #67 is essential, but the expanded data described in #67 MUST be shareable via the pdf.

**Comment by cchristelis** [comment]
This is done in #118.
