### ISSUE TITLE
popup placement

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#70]
larger popups headers go under the top bar. The map should pan to show the whole popup. 

very large popups cross the whole map and you lose control. They should be concertina'd or tabbed or reduced in some way. 

It only seems to behave like this when clicking in the side bar. If you click on the map, it pans properly (though large popups still need to be reduced to fit on the screen.)

**Comment by gubuntu** [comment]
March:
> in cases where the bubble has a lot of information (e.g. Home Page>click on AAA School of Advertising) the bubble positioning is not optimal on a smaller screen.

**Comment by cchristelis** [comment]
fixed in http://staging.feti.kartoza.com/.
