### ISSUE TITLE
duplicate courses?

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#71]
several providers show what appear to be duplicate courses, e.g. 
![screenshot from 2015-06-03 15 51 13](https://cloud.githubusercontent.com/assets/496911/7961546/7fac482e-0a08-11e5-9c75-e75df7209a96.png)

If these are not duplicates, then more fields should be shown to allow them to be discriminated. 

If they are duplicates perhaps we need another round of improving the data import?

**Comment by Gustry** [comment]
These two courses are in the original dataset :
Same ETQA, NQF.
One has a qualification code, which is mapped as NLRD, the other one haven't.
But two different qualification_type : "National Certificate" versus "Clarify (National Certificate)". We don't use the qualification_type in our script.
Should we clean duplicates ?

**Comment by gubuntu** [comment]
I will ask the client, please live with duplicates while we wait for feedback.

**Comment by tmcbride1967** [comment]
Hi. Tim here from FETI. What is missing here are the NQF levels. It is probably the same course, but at different NQF levels. We will need to indicate the levels in the popup box. Thanks

**Comment by tmcbride1967** [comment]
About the (Clarify) National Certificate. Sorry, this was data that we still needed to clean from our side. The "Clarify' was a note to self. (long story).

**Comment by cchristelis** [comment]
@lucernae will have a look at adding the NQF levels next to the courses. From our side there is not much else we can do about data issues.

**Comment by lucernae** [comment]
@tmcbride1967 Should we just show the NQF levels in the popup as: example "NQF level 1" or use the description? In the database, NQF Level 1 will have description something like "Grade 9 / ABET Level 4 / GET Certificate"

**Comment by gubuntu** [comment]
Yes, please add the NQF levels. Data issues will be cleaned up through Django Admin and the back end on an ongoing basis by FETI staff. 

To answer your question above, unless you hear otherwise please use 'NQF Level 1'

**Comment by cchristelis** [comment]
This will no longer be managed by us in this phase.
