### ISSUE TITLE
admin login does nothing

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#73]
I can login now as gavin or March but then just get the same search page with an option to log out. No editing functionality?

Where is Django admin?

**Comment by cchristelis** [comment]
Hi Gavin,

Sorry about that, it seems to be a problem with the redirect. You can use
the manual link for now: http://feti.kartoza.com/feti-admin/

Sincerely,
Christian

- -
------------------------------------------------------------------------------------------
 Christian Christelis - Software Engineer
cell: +27 722 667 344
Skype: christianchristelis
Visit http://kartoza.com to find out about open source:
 * Desktop GIS programming services
 * Geospatial web development
* GIS Training
* Consulting Services
-------------------------------------------------------------------------------------------
 Kartoza is a merger between Linfiniti and Afrispatial
