### ISSUE TITLE
add logos to top bar

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#75]
IPSS and UWC logos are in django_project/feti/static/feti/images/.  

Please provide specs (size and resolution) for final images to be supplied by client. 

also feel free to move the images to a more django-best-practice location in the repo.

**Comment by gubuntu** [comment]
logos are in PR from my fork.

**Comment by lucernae** [comment]
Is this good?
I am using 30px height to achieve somewhat similar composition with [pi.mapaproject.org](http://pi.mapaproject.org/). It would be nice to exclude the letters in the logo because it can't be seen anyway. And perhaps it would be nice to have a transparent background, so the background can blend. Or the logo should have white border surrounding the logo like pi.mapaproject.org did.

![image](https://cloud.githubusercontent.com/assets/831865/8075282/ad5a6930-0f68-11e5-869c-71fd592f2f80.png)

**Comment by lucernae** [comment]
@gubuntu could you look at the logos and tell me if the client is happy with this?

**Comment by gubuntu** [comment]
On 26/06/2015 13:16, Rizky Maulana Nugraha wrote:
>
> @gubuntu <https://github.com/gubuntu> could you look at the logos and
> tell me if the client is happy with this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kartoza/feti/issues/75#issuecomment-115649985>.
>
we'll keep the logos as is until the client provides us with better
quality logos. @cchristelis was going to create a ticket for Maria to
give the design a once-over.

-- 
------------------------------------------------------------------------------------------
Gavin Fleming Joint MD PrGISc [PGP1234]
Visit http://kartoza.com <http://kartoza.com/>to find out about open source:
* Desktop GIS programming services
* Geospatial web development
* GIS Training
* Consulting Services
Skype: phlemingo
-------------------------------------------------------------------------------------------
Kartoza = Linfiniti ∪ Afrispatial

**Comment by gubuntu** [comment]
March has provided [this](https://drive.google.com/file/d/0B3jd4yUoOdXwS2dSQUlTc3gzSTA/view), not sure yet how we are to use it

**Comment by cchristelis** [comment]
This is the logo to use:

![uwc-banner-ipss](https://cloud.githubusercontent.com/assets/2319504/9074480/4c3bff4c-3b0a-11e5-9e25-b70eae67cd54.jpg)

**Comment by cchristelis** [comment]
Hi @MariaSolovyeva, this is a nice logo to add perhaps to the landing page?

**Comment by cchristelis** [comment]
@dimasciput, could you add this logo to the top left of the site.
