### ISSUE TITLE
ensure providers are linked to the correct ETQA

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#85]
This might have already been achieved, but check against the spreadsheets where the client did the mapping of provider to ETQA, to confirm that our database load is doing it correctly. 

In the database we have ETQA as a property of a course. If the mapping is correct then this should still come through when we link courses to providers. If different courses from the same provider have different ETQAs, then Providers could map to different ETQAs and thus cause this issue?

I have asked client for examples of incorrect mapping and clarification about ETQA, so we await that.

**Comment by Gustry** [comment]
> If different courses from the same provider have different ETQAs, then Providers could map to different ETQAs and thus cause this issue?

Does it mean that a provider should match only one ETQA according to them ?
I'm checking the our database.

**Comment by Gustry** [comment]
![feti](https://cloud.githubusercontent.com/assets/1609292/8159174/64093b44-1364-11e5-9e77-e6ddfd5ab4db.png)

As a reminder, we can see two etqa table (the first one on the left and the last one on the right).

**Comment by gubuntu** [comment]
mmm, I'm waiting for feedback from the client about this.

**Comment by gubuntu** [comment]
Apparently we are supposed to be using (or at least guided by) the 'QUERY FOR MARCH' query in the Access database.

In there, Tim (McBride) 
>looked at the DISA MOTORS example, and it records DISA MOTORS under MerSETA (in the "ETQAs_Courses" field)

**Comment by Gustry** [comment]
About DISA Motors, the ETQA is MerSETA in our database. Is it correct ? If yes, maybe they saw this bug before my last fix last week (which was about the ETQA link).

**Comment by gubuntu** [comment]
MerSETA for DISA motors is correct (according to the spreadsheet, which is just a database query export).

AG Training is also showing as MICTSETA (correctly) now.

**Comment by tmcbride1967** [comment]
It is much better than when we first looked. It probably was before Gustry's fix that we looked at it. (we saw this a long while back).

**Comment by cchristelis** [comment]
Hi @tmcbride1967 and @Gustry, is this issue still relevant?

**Comment by gubuntu** [comment]
It seems to be fixed so we'll open again if it reappears
