### ISSUE TITLE
 The GETCA qualifications do not indicate the level. NCV and NATED are missing.

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#86]
@Gustry said:
>About the NCV and NATED, these fields in the COURSE table are empty. Because in the original dataset, I found that NQF, NATED and NCV are in the same field. So I put everything in the NQF table. May we write some regular expression ?
Maybe the frontend (the popup in django) is not set to show  the level ?

**Comment by gubuntu** [comment]
I'm waiting to hear what client means by 'N'

But NCV, NATED, NQF etc are different properties of a course and should not all go in the NQF table.

 - [ ] @lucernae, a course description in the app should pull in the descriptions from all these lookup tables in order to fully describe a course. Can you confirm if it's doing so already?

**Comment by Gustry** [comment]
> But NCV, NATED, NQF etc are different properties of a course and should not all go in the NQF table.

Yes I know. But in the original dataset, all these fields are in the same column, and it is not easy to split this column to many columns, we need to write some regular expression. So as to not loose any data, even if it's wrong temporarily, I put everything in NQF (the most frequently value in the column, so there is a few wrong NCV and NATED).

**Comment by gubuntu** [comment]
ok, so a post cleanup batch job could be done to match values to their respective lookup tables? Let's leave it as is for now.

**Comment by cchristelis** [comment]
Hi @gubuntu and @Gustry, from the chat history it seems like this task is no longer relevant. Any objections to closing this in favour of the feti project team having a look at these data issues?

**Comment by gubuntu** [comment]
OK
