### ISSUE TITLE
We need to clean up the data for the providers - some providers fall under more than one ETQA. (the same provider appears multiple times)

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#87]
@Gustry said:

>In the original dataset, we have a list of campus from the MS Access table called "provider_etqa". We have created the provider table by selecting distinct provider_name on provider_etqa. We didn't care about the ETQA of a provider/campus. I maybe missunderstood the data about this point.
But I remember that I asked you the question about how to split the original table and we decided to use only the name because we didn't know exactly what was a provider according to them. We were wondering if select distinct provider_name was enough.
And I said by mail that we don't know how many providers we should get so as to check that we have some correct results.

>In general, when they write some comments like this, could they provide an example ? (name, id, address...) It's more easier to check (like TVET college above).

**Comment by gubuntu** [comment]
I've asked for examples and clarification. Awaiting feedback

**Comment by cchristelis** [comment]
Hi @gubuntu, this looks like a data issue, which should be fixed in admin interface rather than by a change in the import script. Do you agree?

**Comment by gubuntu** [comment]
Hopefully fixing via admin interface will do the trick, we'll only really tell once admin testing takes place.
