### ISSUE TITLE
Sometimes words are repeated in provider names (e.g. Advanced Advanced)

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#88]
@Gustry  said:
>select * from feti_provider where primary_institution like '%ADVANCED%'; gave me only one result :
 Aerodyne advanced advanced composites (pty) in Stellenbosch : provider id 489.
This line was also in the MS Access database.

**Comment by gubuntu** [comment]
This might well be an app issue. @lucernae can you comment?

**Comment by Gustry** [comment]
'Advanced Advanced' is also in the original dataset. So it's normal that we get 'Advanced Advanced in the app, isn't it ?

**Comment by gubuntu** [comment]
Yes if we can definitely way it's the data in all cases and the app's not doing it then I can tell the client it's a data issue for them to fix. I'll assume that's the case.
