### ISSUE TITLE
Put SETA information at the end of each course and include abbreviation of SETA name

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#90]
We currently put the SETA (ETQA) name in front. Here the client is requesting that its full text and abbreviation go at the end as in these examples:

Skills programme: Fundamental Skills Program (Mathematics):  Agriculture Sector Education and Training Authority (AgriSETA)
National Certificate: Fresh Meat Processing:  Agriculture Sector Education and Training Authority (AgriSETA)
National Certificate: Bread and Flour Confectionery Baking: Agriculture Sector Education and Training Authority  (AgriSETA)

**Comment by tmcbride1967** [comment]
Hi.  Tim here from FETI. Could we rather leave out the full SETA (ETQA) name in the pop up box and just put in the abbreviation (else it becomes cluttered). PS new to Github (bear with me)

**Comment by cchristelis** [comment]
Hi @tmcbride1967, it seems like there has been a little to and for on this. As a reference I am posting our current staging site's (http://staging.feti.kartoza.com/) popup configuration:
![selection_008](https://cloud.githubusercontent.com/assets/2319504/8847082/e9321ee6-312b-11e5-9f83-1eaf8391e05c.png)
Please let me know if this is still too cluttered, if so we will only add the abbreviation.
