### ISSUE TITLE
providers not being grouped, and related issues

### ISSUE THREAD

**Issue by gubuntu** [kartoza/feti#92]
This also might have been fixed with today's commits...

 1. Search for 'adventure site guide' and this provider is returned three times, when instead all its courses should be grouped under one provider instance:

 ```ADVENTURE QUALIFICATIONS NETWORK cc - 1 Riverine Road Parklands```

 1.  These results are also apparently linked to the incorrect ETQA (Public HE)

 1. Some returned providers have no related courses (e.g. Saldanha Steel with engineering courses)

 1. Siyazama also has no related courses but has another problem - a long list of what appear to be exactly the same Fibre Processing courses! So this is an incorrect search result but also emphasises how courses need more complete descriptions, as I'm guessing these are distinguished by NQF level and other factors. 

However, many of the results of this search are good fuzzy matches, so something is working right.

**Comment by lucernae** [comment]
Providers now grouped together. So diferent course list can be from different campus in one provider. So if the course is clicked now, the map will point out to corresponding campus.
